### ISSUE TITLE
Possible errata for "Repository names" limits

### ISSUE THREAD

**Issue by xmo-odoo** [dead-claudia/github-limits#3]
I've been testing the behaviour of the API more in-depth with this help as starting point. I think the current explanation is a bit misleading but I'd like guidance on the subject:

> All characters must be either a hyphen (-), a period (.), or alphanumeric

This is not an actual constraint, because Github will automatically replace anything outside of that set by a `-`.

Also

> Max length: 100 characters

is checked after replacing *sequences* of invalid characters by a single `-`, so e.g. trying to create a repository named `𑣐` repeated 150 times will really create a repository called `-`.

An other possible consideration (though not an error per-se) is the meaning of *character*, which is somewhat imprecise: github seems to work on an exclusive *codepoints* basis, and without any sort of normalisation:

- trying to create a repo called `Åström` using NFC yields `-str-m`, meaning U+00C5 and U+00F6 are each converted to a single `-`
- trying to create a repo called `Åström` using NFD yields `A-stro-m`, meanig U+030A and U+0308 are each converted to a single `-` but the characters they're composed onto are left untouched

**Comment by dead-claudia** [comment]
Feel free to file a pull request with this info.

**Comment by xmo-odoo** [comment]
Sure thing, I mostly opened an issue to know if it was "in scope" so to speak, as I'm not entirely sure how in-details you intend this document to be.
