### ISSUE TITLE
Add things about list of stars

### ISSUE THREAD

**Issue by ccoVeille** [dead-claudia/github-limits#8]
Maximum number of lists in starred items: 32
Maximum length for a list name: 32
Maximum length of the description: 160
Maximum number of starred project per list: ??? my biggest list has 560 items.

These old discussions talk about 16 as a max

https://github.com/orgs/community/discussions/8633
https://github.com/orgs/community/discussions/9513
https://github.com/orgs/community/discussions/9672

but I have already 27. I tested, and I was able to reach 32, then the "Create list" button was deactivated with the mention like "you cannot create more" (I should have taken a screenshot, but I didn't)

I followed the [contributing](https://github.com/dead-claudia/github-limits?tab=readme-ov-file#contributing) section, I can of course open a PR. But I wanted to initiate the discussion here

**Comment by dead-claudia** [comment]
Found an authoritative answer in your first link where a GitHub employee said it was raised to 32 a couple years ago: ~~https://github.com/community/community/discussions/8633#discussioncomment-3164523~~ Corrected link: https://github.com/orgs/community/discussions/8633#discussioncomment-2631870

Feel free to open a PR citing that - I'd happily merge.

**Comment by ccoVeille** [comment]
Are you sure you are referring to the right comment?

The one you quoted is someone who complains, no?

https://github.com/community/community/discussions/8633#discussioncomment-3164523

**Comment by dead-claudia** [comment]
@ccoVeille Oh, I meant to link https://github.com/orgs/community/discussions/8633#discussioncomment-2631870.
